################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/work_dir/projects/testbed/software/robots/software_board/libraries/general/stm32_core_cpp_lib/communication/modbus_rtu/old/Src/Modbus.c \
C:/work_dir/projects/testbed/software/robots/software_board/libraries/general/stm32_core_cpp_lib/communication/modbus_rtu/old/Src/UARTCallback.c 

C_DEPS += \
./stm32_core_cpp_lib/communication/modbus_rtu/old/Src/Modbus.d \
./stm32_core_cpp_lib/communication/modbus_rtu/old/Src/UARTCallback.d 

OBJS += \
./stm32_core_cpp_lib/communication/modbus_rtu/old/Src/Modbus.o \
./stm32_core_cpp_lib/communication/modbus_rtu/old/Src/UARTCallback.o 


# Each subdirectory must supply rules for building sources it contributes
stm32_core_cpp_lib/communication/modbus_rtu/old/Src/Modbus.o: C:/work_dir/projects/testbed/software/robots/software_board/libraries/general/stm32_core_cpp_lib/communication/modbus_rtu/old/Src/Modbus.c stm32_core_cpp_lib/communication/modbus_rtu/old/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H743xx -DRCSTD_CONFIG_BOARD_REV_3 -c -I../Core/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -I"C:/work_dir/projects/testbed/software/robots/software_board/libraries/general/robot-control_std_lib" -I"C:/work_dir/projects/testbed/software/robots/software_board/libraries/general/stm32_core_cpp_lib" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/firmware" -I"C:/work_dir/projects/testbed/software/robots/software_board/libraries/general/stm32_core_cpp_lib/communication/modbus_rtu" -I"C:/work_dir/projects/testbed/software/robots/software_board/libraries/general/stm32_core_cpp_lib/robot/simplexmotion_motors" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/firmware/estimation" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/firmware/control" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/firmware/communication" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/firmware/drive" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/firmware/errors" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/firmware/logging" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/firmware/communication/modules" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/firmware/communication/messages" -I"C:/work_dir/projects/testbed/software/robots/software_board/libraries/general/stm32_core_cpp_lib/utils" -I"C:/work_dir/projects/testbed/software/robots/software_board/libraries/general/stm32_core_cpp_lib/hardware/UART" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32_core_cpp_lib/communication/modbus_rtu/old/Src/UARTCallback.o: C:/work_dir/projects/testbed/software/robots/software_board/libraries/general/stm32_core_cpp_lib/communication/modbus_rtu/old/Src/UARTCallback.c stm32_core_cpp_lib/communication/modbus_rtu/old/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H743xx -DRCSTD_CONFIG_BOARD_REV_3 -c -I../Core/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -I"C:/work_dir/projects/testbed/software/robots/software_board/libraries/general/robot-control_std_lib" -I"C:/work_dir/projects/testbed/software/robots/software_board/libraries/general/stm32_core_cpp_lib" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/firmware" -I"C:/work_dir/projects/testbed/software/robots/software_board/libraries/general/stm32_core_cpp_lib/communication/modbus_rtu" -I"C:/work_dir/projects/testbed/software/robots/software_board/libraries/general/stm32_core_cpp_lib/robot/simplexmotion_motors" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/firmware/estimation" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/firmware/control" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/firmware/communication" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/firmware/drive" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/firmware/errors" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/firmware/logging" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/firmware/communication/modules" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/firmware/communication/messages" -I"C:/work_dir/projects/testbed/software/robots/software_board/libraries/general/stm32_core_cpp_lib/utils" -I"C:/work_dir/projects/testbed/software/robots/software_board/libraries/general/stm32_core_cpp_lib/hardware/UART" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/work_dir/projects/testbed/software/robots/software_board/robots/TWIPR/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-stm32_core_cpp_lib-2f-communication-2f-modbus_rtu-2f-old-2f-Src

clean-stm32_core_cpp_lib-2f-communication-2f-modbus_rtu-2f-old-2f-Src:
	-$(RM) ./stm32_core_cpp_lib/communication/modbus_rtu/old/Src/Modbus.cyclo ./stm32_core_cpp_lib/communication/modbus_rtu/old/Src/Modbus.d ./stm32_core_cpp_lib/communication/modbus_rtu/old/Src/Modbus.o ./stm32_core_cpp_lib/communication/modbus_rtu/old/Src/Modbus.su ./stm32_core_cpp_lib/communication/modbus_rtu/old/Src/UARTCallback.cyclo ./stm32_core_cpp_lib/communication/modbus_rtu/old/Src/UARTCallback.d ./stm32_core_cpp_lib/communication/modbus_rtu/old/Src/UARTCallback.o ./stm32_core_cpp_lib/communication/modbus_rtu/old/Src/UARTCallback.su

.PHONY: clean-stm32_core_cpp_lib-2f-communication-2f-modbus_rtu-2f-old-2f-Src

